### ISSUE TITLE
Skin tone modifiers?

### ISSUE THREAD

**Issue by EyePulp** [wooorm/gemoji#2]
Howdy, I'm using https://github.com/khalifenizar/emoji-strip, which wraps your excellent data.  Right now it doesn't seem to handle skin-tone modifiers which showed up in iOS and OSX recently: http://emojipedia.org/modifiers/

Is this a problem with emoji-strip's implementation, or is it something you'll need to add to gemoji?

Apologies for my ignorance on this stuff.  Thanks for your work. =)

**Comment by wooorm** [comment]
@EyePulp Thanks for the Issue. Also: CC @khalifenizar

`wooorm/gemoji` does indeed *not* support skin-tone modifiers. That’s because it’s a port of [`github/gemoji`](https://github.com/github/gemoji). Now, GitHub doesn’t *yet* support skin-tone modifiers ([#](https://github.com/github/gemoji/pull/72)) or all the new unicode emoji ([#](http://blog.emojipedia.org/unicode-9-emoji-updates/))

My suggestion would be for `emoji-strip` to use the gemoji short-codes (e.g., `:wink:`) from this module and the emoji (with skin-tone-modifiers) from another.
